FROM nginx

# Copy the custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the custom index.html file to the container
COPY index.html /usr/share/nginx/html/index.html
